# Generated by Django 4.2.4 on 2023-08-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='semister',
            new_name='semester',
        ),
    ]
