# Generated by Django 4.2.4 on 2023-08-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_teacherprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stundentprofile',
            name='parents_contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='stundentprofile',
            name='parents_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
